"""federation remote actors

Revision ID: 211d4743f081
Revises: 34508576a6c7
Create Date: 2026-09-25 21:17:31.469467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211d4743f081'
down_revision = '34508576a6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federation_remote_actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(length=2048), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('inbox', sa.String(length=2048), nullable=False),
    sa.Column('shared_inbox', sa.String(length=2048), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('public_key_id', sa.String(length=2048), nullable=False),
    sa.Column('public_key_pem', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gone', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    with op.batch_alter_table('federation_remote_actors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_federation_remote_actors_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_federation_remote_actors_public_key_id'), ['public_key_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('federation_remote_actors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_federation_remote_actors_public_key_id'))
        batch_op.drop_index(batch_op.f('ix_federation_remote_actors_host'))

    op.drop_table('federation_remote_actors')
    # ### end Alembic commands ###
