"""now playing

Revision ID: 2533b727da79
Revises: 0b81b61c932a
Create Date: 2026-09-26 16:54:40.320486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2533b727da79'
down_revision = '0b81b61c932a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federation_now_playing',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_key', sa.String(length=512), nullable=True),
    sa.Column('profile_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('post_key', sa.String(length=512), nullable=True),
    sa.Column('post_posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('federation_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('now_playing_mode', sa.String(length=16), nullable=False, server_default='off'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('federation_settings', schema=None) as batch_op:
        batch_op.drop_column('now_playing_mode')

    op.drop_table('federation_now_playing')
    # ### end Alembic commands ###
