"""federation settings and keys

Revision ID: 34508576a6c7
Revises: federation_0001
Create Date: 2026-09-25 20:18:10.573299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34508576a6c7'
down_revision = 'federation_0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federation_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('public_key_pem', sa.Text(), nullable=False),
    sa.Column('private_key_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('federation_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('manually_approves_followers', sa.Boolean(), nullable=False),
    sa.Column('discoverable', sa.Boolean(), nullable=False),
    sa.Column('indexable', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('federation_settings')
    op.drop_table('federation_keys')
    # ### end Alembic commands ###
