"""album art cache

Revision ID: 3ba21eb1ea0c
Revises: e7fb730bac15
Create Date: 2026-10-06 16:58:58.755196

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3ba21eb1ea0c"
down_revision = "e7fb730bac15"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "album_art",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artist", sa.Text(), nullable=False),
        sa.Column("album", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("release_group_mbid", sa.String(length=36), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("album_art", schema=None) as batch_op:
        batch_op.create_index(
            "uq_album_art_artist_album_lower",
            [sa.literal_column("lower(artist)"), sa.literal_column("lower(album)")],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("album_art", schema=None) as batch_op:
        batch_op.drop_index("uq_album_art_artist_album_lower")

    op.drop_table("album_art")
    # ### end Alembic commands ###
