"""federation followers inbox deliveries

Revision ID: a481855fcb93
Revises: 211d4743f081
Create Date: 2026-09-25 21:22:22.746321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a481855fcb93'
down_revision = '211d4743f081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federation_inbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.String(length=2048), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('actor_uri', sa.String(length=2048), nullable=False),
    sa.Column('inbox_path', sa.String(length=512), nullable=False),
    sa.Column('headers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('body', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id')
    )
    with op.batch_alter_table('federation_inbox', schema=None) as batch_op:
        batch_op.create_index('ix_federation_inbox_status_received', ['status', 'received_at'], unique=False)

    op.create_table('federation_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('document', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('federation_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_federation_activities_user_id'), ['user_id'], unique=False)

    op.create_table('federation_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('remote_actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['remote_actor_id'], ['federation_remote_actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'remote_actor_id', name='uq_federation_block')
    )
    with op.batch_alter_table('federation_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_federation_blocks_user_id'), ['user_id'], unique=False)

    op.create_table('federation_followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('remote_actor_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('follow_activity_id', sa.String(length=2048), nullable=False),
    sa.Column('follow_activity', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['remote_actor_id'], ['federation_remote_actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'remote_actor_id', name='uq_federation_follower')
    )
    with op.batch_alter_table('federation_followers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_federation_followers_user_id'), ['user_id'], unique=False)

    op.create_table('federation_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('inbox', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_status', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['federation_activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'inbox', name='uq_federation_delivery')
    )
    with op.batch_alter_table('federation_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_federation_deliveries_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index('ix_federation_deliveries_due', ['status', 'next_attempt_at'], unique=False)

    with op.batch_alter_table('federation_remote_actors', schema=None) as batch_op:
        batch_op.alter_column('inbox',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.String(length=1024),
               existing_nullable=False)
        batch_op.alter_column('shared_inbox',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.String(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('federation_remote_actors', schema=None) as batch_op:
        batch_op.alter_column('shared_inbox',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)
        batch_op.alter_column('inbox',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=False)

    with op.batch_alter_table('federation_deliveries', schema=None) as batch_op:
        batch_op.drop_index('ix_federation_deliveries_due')
        batch_op.drop_index(batch_op.f('ix_federation_deliveries_activity_id'))

    op.drop_table('federation_deliveries')
    with op.batch_alter_table('federation_followers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_federation_followers_user_id'))

    op.drop_table('federation_followers')
    with op.batch_alter_table('federation_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_federation_blocks_user_id'))

    op.drop_table('federation_blocks')
    with op.batch_alter_table('federation_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_federation_activities_user_id'))

    op.drop_table('federation_activities')
    with op.batch_alter_table('federation_inbox', schema=None) as batch_op:
        batch_op.drop_index('ix_federation_inbox_status_received')

    op.drop_table('federation_inbox')
    # ### end Alembic commands ###
